CREATE DATABASE RKFHE0;

CREATE TABLE TULAJDONOS (
tkód INT(3),
név VARCHAR(20),
város VARCHAR(20),
PRIMARY KEY(tkód));

CREATE TABLE AUTO(
rendszám CHAR(7),
típus VARCHAR(25),
szín VARCHAR(15),
ár INT(8),
kor INT(2),
tulaj INT (3),
PRIMARY KEY (rendszám),
FOREIGN KEY(tulaj) REFERENCES TULAJDONOS(tkod));



INSERT INTO TULAJDONOS VALUES(101,'Kis János','Miskolc');
INSERT INTO TULAJDONOS VALUES(102,'Kis Éva','Szerencs');
INSERT INTO TULAJDONOS VALUES(103,'Retek Ödön','Miskolc');
INSERT INTO TULAJDONOS VALUES(104,'Virág Zoltán','Nyék');
INSERT INTO TULAJDONOS VALUES(105,'Nagy Eszter','Nyék');
INSERT INTO TULAJDONOS VALUES(106,'Kovács Magor','Szerencs');
INSERT INTO TULAJDONOS VALUES(107,'Asztal Antal','Miskolc');

INSERT INTO AUTO VALUES('FER-831','Opel Corsa','Piros',18,390,101);
INSERT INTO AUTO VALUES('GDF-525','Renault Twingo','Fekete',16,280,NULL);
INSERT INTO AUTO VALUES('HUB-936','Suzuki Swift','Fekete',16,500,NULL);
INSERT INTO AUTO VALUES('IXL-239','Suzuki Swift','Zöld',15,450,105);
INSERT INTO AUTO VALUES('JAH-425','Skoda Fabia','Piros',13,620,102);
INSERT INTO AUTO VALUES('JCD-443','Opel Astra','Fehér',12,990,107);
INSERT INTO AUTO VALUES('KAP-290','BMW 316','Fekete',6,3250,102);
INSERT INTO AUTO VALUES('KFT-204','Opel Astra','Szürke',7,1250,106);
INSERT INTO AUTO VALUES('MLM-211','Toyota Yaris','Fehér',3,1850,105);